---
env:
  TERM: xterm-256color
  # TERM: alacritty
  # Neomutt resets colors so following is a workaround for:
  # https://github.com/neomutt/neomutt/issues/518
  # TERM: screen-256color

scrolling:
  history: 10000
  multiplier: 3

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: SauceCodePro Nerd Font Mono
    style: Regular
  bold:
    family: SauceCodePro Nerd Font Mono
    style: Bold
  italic:
    family: SauceCodePro Nerd Font Mono
    style: Light Italic
  size: 10.5
  scale_with_dpi: true
  use_thin_strokes: true
