---
env:
  TERM: xterm-256color
  # TERM: alacritty
  # Neomutt resets colors so following is a workaround for:
  # https://github.com/neomutt/neomutt/issues/518
  # TERM: screen-256color

scrolling:
  history: 10000
  multiplier: 3

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: SauceCodePro Nerd Font Mono
    style: Regular
  bold:
    family: SauceCodePro Nerd Font Mono
    style: Bold
  italic:
    family: SauceCodePro Nerd Font Mono
    style: Light Italic
  size: 7.5
  scale_with_dpi: true
  use_thin_strokes: true
debug.render_timer: false

custom_cursor_colors: false

mouse_bindings:
  - {mouse: Middle, action: PasteSelection}

mouse:
  double_click: {threshold: 300}
  triple_click: {threshold: 300}
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

hide_cursor_when_typing: true
cursor_style: Block
unfocused_hollow_cursor: true
live_config_reload: true
bell:
  animation: EaseOutExpo
  duration: 0
